### ISSUE TITLE
정보전달 페이지 내용 정리

### ISSUE THREAD

**Issue by geniusgo** [DublinCity/jayang-front#3]
- [ ] 정보 페이지 반영 (혜린이가 디자인 한 번 봐주면 좋을듯)
- [ ] 메인 이미지 반영 (보경이가 준 이미지, <묵은땅을 기경하라> 타이틀 폰트 확인 필요
- [ ] 메인 레이아웃 변경 (버튼 네 개 나란히, 이건 따로 레이아웃 안 잡아줘도 되나?)
- [ ] 핵심가치 다섯개로 (적절한 아이콘 하나 추가 필요)

![프로그램-안내](https://user-images.githubusercontent.com/63655250/79243092-23e86c80-7eb0-11ea-9e1d-e6199bc3009d.jpg)
![공동체-소개](https://user-images.githubusercontent.com/63655250/79243102-264ac680-7eb0-11ea-9941-9cd022bf1a84.jpg)
![교육-안내](https://user-images.githubusercontent.com/63655250/79243283-64e08100-7eb0-11ea-8112-021534fa0633.jpg)
![메인_1](https://user-images.githubusercontent.com/63655250/79243460-9bb69700-7eb0-11ea-9c50-778aa10850f8.jpg)
![메인_2](https://user-images.githubusercontent.com/63655250/79243478-a2450e80-7eb0-11ea-9b5c-e5a865d12fa9.jpg)

**Comment by DublinCity** [comment]
@geniusgo 해상도 때문에, 이미지 원본 파일 받을 수 있어?

**Comment by DublinCity** [comment]
@geniusgo 아래처럼 하려는거 맞을까? 
- pc
![image](https://user-images.githubusercontent.com/31264833/79284735-83696b00-7ef6-11ea-893f-b02830477bb7.png)
- mobile
![image](https://user-images.githubusercontent.com/31264833/79284857-d7744f80-7ef6-11ea-9ac9-d040e42e7707.png)
