### ISSUE TITLE
테마를 사용해 주세요.

### ISSUE THREAD

**Issue by Jonir227** [DublinCity/jayang-front#6]
https://github.com/DublinCity/jayang-front/blob/c6a479e4e91fd58b30ec355ccca2627a7e30debc/src/GlobalStyle.tsx#L12

https://styled-components.com/docs/advanced#theming

테마를 사용하면 색상을 쉽게 가져올 수 있습니다.

**Comment by DublinCity** [comment]
@Jonir227 
코멘트 감사합니다! 9540e3b 커밋으로 적용했습니다

**Comment by Jonir227** [comment]
감사하빈다.

**Comment by DublinCity** [comment]
@Jonir227 계속 감시부탁드립니다.
